require("yogan.autocmds")
require("yogan.filetype")
require("yogan.functions")
require("yogan.globals")
require("yogan.keymaps")
require("yogan.neovide")
require("yogan.options")
require("yogan.plugins")
